language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.10"
  - "5.8"

install:
  - cpanm -v --installdeps --notest --mirror http://cpan.mirrors.travis-ci.org .


notifications:
  recipients:
    - limitusus@cpan.org
  email:
    on_success: change
    on_failure: always

